"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tsyringe_1 = require("tsyringe");
const permission_group_repository_prisma_1 = require("@/infra/database/orms/prisma/repositories/permission.group.repository.prisma");
const create_permission_group_usecase_1 = require("../usecases/create.permission.group.usecase");
const permission_group_repository_1 = require("../repositories/permission.group.repository");
const find_all_permission_rules_usecase_1 = require("../usecases/find.all.permission.rules.usecase");
const permission_rule_repository_1 = require("../repositories/permission.rule.repository");
const permission_rule_repository_prisma_1 = require("@/infra/database/orms/prisma/repositories/permission.rule.repository.prisma");
const permission_group_rule_repository_1 = require("../repositories/permission.group.rule.repository");
const permission_group_rule_repository_prisma_1 = require("@/infra/database/orms/prisma/repositories/permission.group.rule.repository.prisma");
const paginate_permission_groups_usecase_1 = require("../usecases/paginate.permission.groups.usecase");
tsyringe_1.container.registerSingleton('CreatePermissionGroupUseCase', create_permission_group_usecase_1.CreatePermissionGroupUseCase);
tsyringe_1.container.registerSingleton('PaginatePermissionGroupsUseCase', paginate_permission_groups_usecase_1.PaginatePermissionGroupsUseCase);
tsyringe_1.container.registerSingleton('PermissionGroupRepository', permission_group_repository_1.PermissionGroupRepository);
tsyringe_1.container.registerSingleton('PermissionGroupRepositoryInfra', permission_group_repository_prisma_1.PermissionGroupRepositoryPrisma);
tsyringe_1.container.registerSingleton('FindAllPermissionRulesUseCase', find_all_permission_rules_usecase_1.FindAllPermissionRulesUseCase);
tsyringe_1.container.registerSingleton('PermissionRuleRepository', permission_rule_repository_1.PermissionRuleRepository);
tsyringe_1.container.registerSingleton('PermissionRuleRepositoryInfra', permission_rule_repository_prisma_1.PermissionRuleRepositoryPrisma);
tsyringe_1.container.registerSingleton('PermissionGroupRuleRepository', permission_group_rule_repository_1.PermissionGroupRuleRepository);
tsyringe_1.container.registerSingleton('PermissionGroupRuleRepositoryInfra', permission_group_rule_repository_prisma_1.PermissionGroupRuleRepositoryPrisma);
